services:
  manga-reader:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SUWAYOMI_SERVER_URL: ${SUWAYOMI_SERVER_URL:-}
    image: manga-reader:latest
    container_name: manga-reader
    restart: unless-stopped
    ports:
      - "3000:4173"
    environment:
      - SUWAYOMI_SERVER_URL=${SUWAYOMI_SERVER_URL:-}
